\begin{abstract}
These notes accompany the "Multimessenger Astronomy" lecture from the \emph{Gravitational Wave Detection} (PHYS 5006) course, taught at the University of Glasgow in the Autumn term, 2019. You shouldn't consider these notes comprehensive: the field of multimessenger astronomy is developing rapidly.  The bibliography of these notes could be a useful starting-point for a more comprehensive exploration of the literature, however.
\end{abstract}



The advent of the first binary neutron star observation, GW170817 cite:2017PhRvL.119p1101A, to be observed by abbr:gw detectors served as the advent of a new era in observational astrophysics, with abbr:gw now able to sit alongside conventional electromagnetic observations to probe the astrophysical nature of some of the most extreme events in the universe.

When the same astrophysical object or event is observed through multiple different observational approaches, or /messengers/ the event is deemed to be a abbr:mma event.
There are four messengers of which observations are currently made: abbr:em radiation, abpl:gw, abpl:hen, and cosmic rays [fn:heliosphere].

[fn:heliosphere] Within the solar system, and more broadly, the heliosphere, it's possible to argue that additional messengers exist, for example, through sample return missions, or magnetometer measurements, however, these are not available for the vast majority of the universe, so I'll not give them any further consideration here.

* Multimessenger astronomy: A very brief history

While the discovery of GW170817 marked the beginning of abbr:mma with abpl:gw, it did not mark the beginning of abbr:mma as a field.
The earliest abbr:mma observations can be traced to astroparticle observations of the solar flares in the 1940s cite:2015paas.book.....S.
The observation of SN1987A, a type-II supernova in the Large Magellanic Cloud, was made first in visible light at Las Campanas, but also later in ultraviolet. Around three hours prior to the event's detection in abbr:em, a number of abbr:hen observatories detected a burst of antineutrinos (with around 25 particles observed across three observatories).
The first detection of gravitational waves was made in 2015, with the observation of a abbr:bbh coalescence, and just under two years later the first observation of abpl:gw from a abbr:bns coalescence was made, which coincided with a abbr:sgrb observed by the Fermi satellite. 
An extensive observing campaign was launched as a result of these observations, with observatories covering the entire abbr:em spectrum making observations of the event. 
These will be discussed in detail in the section discussing GW170817.


* Multimessenger astrophysical sources

The anticipated sources of gravitational wave signals fall into two broad categories: transient sources, which produce a burst of abpl:gw over a short period of time; and abbr:cw sources, which produce abpl:gw continuously.
A number of transient sources are considered as promising targets for abbr:mma astronomy, and these are often referred to as /abbr:em bright/.

** Black hole coalescences

\marginpar{
\begin{tabular}{cccc}
 EM  & GW   & HEN & CR \\
 No  & Yes  & No  & No
\end{tabular}

abbr:bbh events are not generally anticipated to be promising sources for abbr:em emission, despite being the most frequently observed source of abpl:gw, and the result of the most energetic events in the observed universe.
There has, however, been speculation that under certain circumstances abbr:em emission could be produced as a result of a abbr:bbh coalescence cite:2016ApJ...819L..21L,2017ApJ...839L...7D, partly driven by the apparent observation of gamma rays around \SI{0.4}{\second} following the abbr:gw signal from GW150914 cite:2016ApJ...826L...6C [fn:gw150914em].

[fn:gw150914em] Though it's generally accepted that this was a coincidence, as no abbr:bbh event following this one has been coincident with an abbr:em event, and the poor localisation of the GW150914 signal provides little evidence that the two events were spatially coincident.

** Neutron star coalescences

\begin{tabular}{cccc}
 EM   & GW   & HEN & CR \\
 Yes  & Yes  & ?   & No
\end{tabular}

In contrast to abbr:bbh coalescences, abbr:bns mergers are expected to produce large quantities of abbr:em radiation. These have long been assumed to be the source of abpl:sgrb, and the observation of GW170817 provided strong confirmation that they are the engine for at least a subset of observed abpl:sgrb.

 - abbr:sgrb :: The initial abbr:em emission is expected to be from high-energy, collimated gamma rays from the initial fireball.
 - kilonova :: UV through IR emission from nuclear processes in the ejecta cite:2010MNRAS.406.2650M.
 - radio emission :: Resulting from the interaction of the jet with the interstellar medium.

** Supernovae
\begin{tabular}{cccc}
 EM   & GW   & HEN & CR \\
 Yes  & ?    & Yes  & No
\end{tabular}

abbr:em emission from supernova has been observed since 1064CE, when the abbr:sn which created the Crab Nebula occurred and was observed by astronomers in China (although an event in 0185 which was also observed in China may also have been a supernova).
The first abbr:mma observation of a abbr:sn occurred in 1987, SN 1987A, which was close enough (in the Large Magellanic Cloud) that it could be observed in detail as it evolved.
abpl:sn are known to emit thermal neutrinos (neutrinos were detected from SN 1987A cite:1988PhRvD..38..448H) and there are potential mechanisms for the production of high energy neutrinos in abpl:sn as well cite:2019arXiv190712506M.
We expect abbr:gw to be produced during a core-collapse abbr:sn thanks to the asymmetrical nature of the explosion, but the physics of abbr:sn are poorly understood, and as a result the strength of abbr:gw signals from abpl:sn is unknown.

** Blazars
\begin{tabular}{cccc}
 EM	& GW	& HEN  & CR \\
 Yes  	& No    & Yes  & ?
\end{tabular}

A blazar is an abbr:agn with a relativistic jet which is directed towards the observer.
A muon neutrino was detected from the blazar =TXS 0506+056= on 22 September 2017: the blazar had previously been observed in radio, but this was the first detection of a abbr:hen source.
=TXS 0506+056= is also a gamma ray source, and the 2017 neutrino event coincided with it flaring in gamma rays. 
This some evidence that =TXS 0506+056= should be a source of pions, since the production of abbr:hen is likely a result of pion decay. 
No cosmic rays from this source have been observed, however.

** Pulsars
\begin{tabular}{cccc}
 EM	& GW   & HEN	& CR \\
 Yes  	& ?    & No  	& No
\end{tabular}

Pulsars are neutron stars which produce a relativistic jet which can be observed in radio.
Neutron stars are known to be extremely spherical, however any ellipticity or irregularities in the shape (like mountains) will result in the star having a quadrupole moment, and therefore producing abpl:gw as it rotates.
To date no abpl:gw from pulsars have been observed, and this allows an upper limit to be placed on the size of any mountains on the surface of nearby pulsars (as of O2 the largest mountain would be around $\SI{5}{\centi\meter}$ \cite{2019PhRvD..99l2002A} [fn:mountain-earthscale]).

[fn:mountain-earthscale] If the Earth was equivalently spherical the highest mountains would be around $\SI{25}{\meter}$ high.

* Preparing GW alerts

While abbr:gw detections can be interesting in their own right, the development of abbr:mma relies on rapid communication between the abbr:gw detectors and abbr:em observatories.
This is challenging, as not all abbr:gw events are likely to produce abbr:em emission, and the location of the event in the sky must be determined.
Once these quantities are determined abbr:gw events are reported using the abbr:gcn and on \texttt{GraceDB} (see \url{https://gracedb.ligo.org/superevents/public/O3/}).

** Localising GW signals on the sky

If a network of at least two geographically separated detectors observes a signal it is possible to ascertain the location in the sky, $\hat{\vec{\Omega}}$, from the difference in arrival times between the two sites.
For a detector at a position, $\vec{r}_{D}$, and an arbitrary reference location, $\vec{r}_{0}$, this time delay, $\delta t$, will be
\begin{equation}
\label{eq:intro:detectors:timedelay}
\delta t (\hat{\vec{\Omega}}) = \frac{1}{c} (\vec{r}_{0} - \vec{r}_{D}) \cdot \hat{\vec{\Omega}}.
\end{equation}
This allows the location of the signal to be confined to a ring on the sky corresponding to constant $\Delta t$.
Examples of these rings for a abbr:gw source are plotted in figure ref:fig:det:advanced-timing.
Timing uncertainty in the signal, which arises both from clock uncertainties and uncertainties in defining a reference point in the received signal increase the area of this region.
As more detectors are added to the network it is possible to reduce this area, as increasing the number of detector pairs works to reduce the sky area compatible with the observed delay times.

\begin{figure}
\includegraphics{figures/timing-circles}
\caption{Isochrones for the three detector pairs in the advanced network. 
For a single detector pair the localisation is a ring; with three detectors there are three pairs of detectors, and so three rings, and we can reduce the plausible locations the signal could have come from to the two places where all of the rings overlap.
}
\label{fig:det:advanced-timing}
\end{figure}

Additional localisation information can be attained from the observed amplitude of the signal in each detector.
The signal will be convolved with the antenna pattern (see figure ref:fig:det:aligo-antenna); as each detector is insensitive to some regions of the sky, the total plausible localisation of the signal is reduced.

For a abbr:gw approaching the detector from an azimuth (relative to one of the arms) and altitude (relative to the plane of the detector), $(\alpha, \delta)$ on the sky these patterns for the $+$- and $\times$-polarisations, $F_{+}$ and $F_{\times}$, will be 
\begin{subequations}
\begin{align}
\label{eq:detectors:antennapattern:plus}
F_{+} &= \frac{1}{2} (1 + \sin^{2}\delta) \cos 2\alpha \cos 2\psi - \sin\delta\sin 2 \alpha \sin 2 \psi \\
F_{\times} &=  \frac{1}{2} (1 + \sin^{2}\delta) \cos 2\phi \sin 2\psi - \sin\delta\sin 2 \phi \cos 2 \psi.
\end{align}
\end{subequations}
where $\phi$ is the polarisation angle of the abbr:gw.

\begin{figure}
\includegraphics{figures/aligo-antenna-pattern}
\caption{Antenna pattern of an aLIGO detector, normalised so that the locations which the detection is most sensitive to are labelled $1$, and those it is insensitive to are labelled $0$. }
\label{fig:det:aligo-antenna}
\end{figure}

** Determining EM bright

It's important to be able to determine if the source of a abbr:gw is likely to produce abbr:em radiation which can be observed by conventional observatories.
An important part of this is determining if the source of a signal was a abbr:bbh or a abbr:bns.
To do this we need to consider two quantities: the gls:chirp-mass of the system, which can be measured directly from the waveform, and the compactness of the system, which can be determined by identifying the moment that the system merges in the waveform.

The gls:chirp-mass, $\chirpmass$, can be determined if the frequency, $f_{\text{GW}}$, and the frequency derivative, $\dot{f}_{\text{GW}}$, with respect to time of the abbr:gw are measured cite:2017AnP...52900209A:

\begin{equation}
\label{eq:chirp-mass-frequency}
\chirpmass = \frac{c^3}{G} \left[ \left( \frac{5}{96} \right)^{3} \pi^{-8} f_{\text{GW}}^{-11} \dot{f}_{\text{GW}}^{3} \right]^{1/5}.
\end{equation}

This can be integrated with respect to time to remove the explicit dependence on $\dot{f}_{\text{GW}}$:
\begin{equation}
\label{eq:chirp-mass-frequency-int}
f_{\text{GW}}^{-8/3} (t) = \frac{(8 \pi)^{8/3}}{5} \left( \frac{G \chirpmass}{c^3} \right)^{5/3} (t_{\text{c}} - t),
\end{equation}
where $t_{\text{c}}$ is the time at which the two objects coalesce. 
Thanks to this equation it is possible to determine the chirp mass using the time periods between zero-crossings of the signal.

The gls:chirp-mass gives an important indicator that a system is a abbr:bbh rather than a abbr:bns, since there are good physical reasons to believe neutron stars have an upper mass limit (the Tolman-Oppenheimer-Volkoff limit) around $2.17\,\solMass$. 
It does not, however, exclude the system being the result of two low-mass black holes coalescing.
To exclude this possibility we must calculate the compactness of the binary close to the merger: black holes are physically denser and more compact than neutron stars, and so can produce a more compact orbit before merging.

The compactness of the system will be affected by spin and orbital eccentricity, but for simplicity we can consider the compactness of a non-spinning system where the orbit close to the merger is almost circular [fn:basic-physics-spin].
This can be determined by measuring the frequency of the orbit immediately prior to the merger, $\omega_{\text{max}}$, which coincides with the time when the abbr:gw amplitude is greatest (recalling that the abbr:gw frequency is *twice* the orbital frequency).
The orbital separation, $R$ of the objects in the binary is 
\begin{equation}
\label{eq:oribital-separation}
R = \left( \frac{GM}{\omega_{\text{max}}^2} \right),
\end{equation}
where $M$ is the total mass of the binary.

For a abbr:bbh similar to GW150914, where $M \approx 70\,\solMass$ we find that $R = \SI{350}{\kilo\meter}$: this is small in comparison to the normal diameters of stars, but it's a little difficult to see the implications of this for compact objects.

To help with this we introduce the compactness ratio, $\mathcal{R}$, which is the ratio of $R$ to the Schwarzchild radius, which is the smallest possible radius of a compact object.

\begin{equation}
r = \frac{2Gm}{c^{2}} \approx 2.95 \left( \frac{m}{\solMass} \right) \,\text{km}
\end{equation}

In the GW150914-like case above $\mathcal{R} \approx 1.7$, since the Schwarzchild radius of the individual objects is $\SI{103}{\kilo\meter}$.
For a abbr:bns system we expect $\mathcal{R}$ between around $2$ and $5$.

[fn:basic-physics-spin] For a fuller discussion of the effects of spin and the orbit on the determination of the orbital compactness see section 4 of cite:2017AnP...52900209A.

* Transient astronomy
** Gamma-ray burst observatories

There are currently four major gamma-ray burst observatories located on Earth-orbitting satellites.

+ abbr:bat :: A gamma ray detector on the Neil Gehrels /Swift/ Observatory with a large field of view (over 1 steradian with high positional accuracy, and three with lower accuracy--the whole sky is $4 \pi$ steradians) which can roughly localise a abbr:grb within 15 seconds.
+ abbr:gbm :: A gamma ray detector on the Fermi Gamma-ray Space Telescope which is composed of twelve scintillation detectors giving whole-sky coverage (except for the part of the sky obscured by the Earth).
+ INTEGRAL :: The INTEGRAL satellite, like gls:gbm, provides all-sky coverage and localisation of abpl:grb.
+ AGILE ::  A gamma ray telescope with a narrower field of view than the other three instruments which are dedicated to abbr:grb detection, but which has observed a large number of abpl:grb.

The proposed THESEUS mission, under development by the European Space Agency is a abbr:grb and X-ray observatory planned for launch around 2032.
The timing of this mission's launch would mean that both THESEUS and gls:lisa would be observing simultaneously.

** Optical surveys
   Optical surveys are an important aspect of transient astronomy, and they promise to allow very rapid detection of short-lived astrophysical events such as supernovae and kilonovae.
   While sky surveys are nothing new in the world of astronomy, dating back to the development of catalogues such as Messier's in the 18th Century, the ability to conduct a survey over a very large area of the sky very rapidly has only become possible thanks to development in both sensor technology and data processing techniques in the last decade.
   A current example of such a survey telescope is the abbr:ztf cite:2014htu..conf...27B, which is capable of imaging a 47 square degree area of the sky in a single exposure, allowing the entire Northern hemisphere sky to be imaged every three nights, to a limiting magnitude around 20.5. 
   The abbr:ztf produces large quantities of data every night, but this will be dwarfed by the quantity of data produced by the abbr:lsst.
   This facility, which has been designed specifically for rapid all-sky surveys (compared to abbr:ztf, which is an instrument placed on an exisiting telescope) will produce around ten times more data, around 15 terabytes per night, proving a formidable challenge to both data processing and analysis.
   Other important programmes in transient astronomy include the One-Meter Two-Hemisphere collaboration (comprising the Swope Supernova Survey in Chile, and the Nickel Telescope in California) who were the first to discover the optical counterpart to GW170817 cite:2017Sci...358.1556C, and on a somewhat longer timescale, ESA's \emph{Gaia} mission cite:2019IAUS..339...12B.


* Challenges for GW event follow-up

While preparing alerts based on abbr:gw observations is challenging, attempting to make abbr:em observations to follow these up is not without problems.
The localisation of most abbr:gw events is poor, meaning that the event could originate anywhere within a large patch (or large patches) of the sky.
The majority of abbr:em observatories can perform observations over only a small field of view, however, and the abbr:em emission related to a abbr:gw event may be short-lived.
As a result an abbr:em observatory must be able to rapidly survey a large area of sky with high sensitivity.

The sky localisations which are published by abbr:gw detectors are divided into observing "tiles" by each follow-up observatory cite:2016A&A...592A..82G.
The size of each tile will vary depending on the sensitivity and field-of-view of the telescope.
Each tile is then prioritised using probability information from the abbr:gw analysis cite:2017ApJ...834...84C,2019MNRAS.489.5775C, and taking into account difficulties in moving the telescope and the period of local night.



* GW170817: A case-study
\label{sec:gw170817}

\begin{figure*}
\includegraphics[width=\textwidth]{figures/gw170817-localisation.pdf}
\caption{The sky localisation for GW170817. The localisation region from the two LIGO detectors is shown in light green, and from the LIGO and Virgo network in dark green.
The light blue band is the localisation derived from the time delay between the Fermi and INTEGRAL observations of the \gls{sgrb}, GW 170817A. The images on the right are the first optical observation by Swope [top], and an image of the same galaxy taken 21 days prior to the event by the DLT40 survey. This figure is reproduced from figure 1 of~\cite{2017ApJ...848L..12A}.
 \label{fig:gw170817-localisation}}
\end{figure*}


On 17 August 2017, during the second observing run of advanced LIGO, and a few days after advanced Virgo had started making observations a abbr:gw signal, GW170817, was detected by both LIGO detectors and the Virgo detector.
In contrast to previous abbr:gw detections which had all been abbr:bbh signals, GW170817 was identified as being produced by a abbr:bns system.

Independently of the abbr:gw detection the Fermi and INTEGRAL satellites detected a abbr:sgrb slightly less than two seconds after the time the abbr:bns was detected in abpl:gw.
GCN alerts were issued rapidly for both the Fermi abbr:sgrb detection (within 14 seconds) and the LIGO/Virgo abbr:gw detection (within 40 minutes).



The (recently-expanded) three detector abbr:gw network initially localised the signal to within 31 square degrees in the southern celestial hemisphere, however later analysis allowed this to be reduced to a 28 square degree patch of sky.
The localisation areas from the various detections are shown in figure ref:fig:gw170817-localisation for the abbr:gw detections in green and the abbr:sgrb detections in blue.

The three-detector localisation was calculated by around 17:54 UTC, which allowed telescopes in South America to search the localisation area for an optical transient [fn:sun].
The Swope supernova survey was the first collaboration to observe the transient cite:2017ApJ...848L..12A,2017Sci...358.1556C (although six observatories would independently discover the optical counterpart cite:2017ApJ...848L..12A).
The optical counterpart was observed in NGC 4993.

The highly-precise localisation which was produced by imaging the optical counterpart allowed observations to be made across the entire abbr:em spectrum.

Ultraviolet emission was detected 15.3 hours after the event by Swift, and 9 days later X-ray emission was detected by the Chandra X-ray Observatory. 
16 days after the abbr:bns was observed radio emission was observed by the VLA in New Mexico.

abbr:em observations continued until 2019, with the Hubble Space Telescope unable to detect any optical afterglow after 584 days cite:2019ApJ...883L...1F.
Superluminal radio emission was also reported cite:2018Natur.561..355M between 75 and 230 days after the abbr:bns merger.


[fn:sun] The search was complicated by the proximity of the search region to the sun, which meant observations were only possible shortly after the onset of twilight for optical telescopes.

# \begin{figure*}
# \includegraphics[width=\textwidth]{figures/gw170817-gcn-timeline.pdf}
# \caption{The timeline of GCN notices from GW170817 and its assosciated electromagnetic events.
# Reproduced from figure 2 of~\cite{2017ApJ...848L..12A}.
# \label{fig:170817-gcn}
# } 
# \end{figure*}

* Cosmology from multimessenger astronomy

The observation of an abbr:em counterpart to GW170817 allowed the galaxy it originated in to be identified.
In turn this allowed the recession velocity of the abbr:bns to be determined with high precision from its redshift.
The abbr:gw detection allows the distance to the source to be measured directly (although with a fairly large uncertainty, thanks to a degeneracy between the distance to the source and the angle at which it is inclined relative to the observer.

Since the distance, $d$, and recession velocity, $v$, are related by Hubble's Law,

\begin{equation}
\label{eq:hubble-law}
v = H_{0} d
\end{equation}

if we know both $v$ and $d$ we can infer $H_{0}$.

The distance to the source of GW170817 inferred from the abpl:gw is $d = \SI[parse-numbers=false]{48.8^{+2.9}_{-6.9}}{\mega\parsec}$, and the measured recession velocity is $v = \SI{3017\pm166}{\kilo\meter\ \second^{-1}}$.

This allowed $H_{0}$ to be inferred to be $\SI[parse-numbers=false]{70.0^{+12.0}_{-8.0}}{\kilo\meter\ \second^{-1}\ \mega\parsec^{-1}}$ \cite{2017Natur.551...85A}.

\begin{figure}
\includegraphics[width=\textwidth]{figures/H0-inference}
\caption{The posterior probability density function of the inferred value of the Hubble constant, $H_{0}$ using observations of GW170817, compared to the value inferred from Planck observations of the cosmic microwave background (green) and from supernovae (orange). The \gls{gw}-based inference is not sufficiently precise to resolve the tension between these two estimates.
}
\label{fig:h0-inference}
\end{figure}

While we get the greatest amount of information from events which can be localised by abbr:em observations, it is also possible to infer the Hubble constant using only abbr:gw observations.
This means that abbr:bbh events can be used, which are much more frequently observed than abbr:bns events.

In order to make inferences without knowing which galaxy the event occurred in we need accurate three-dimensional galaxy catalogues.
By identifying a list of galaxies which lie within the localised volume (through the sky localisation and distance estimate of the abbr:gw) we can use a Bayesian analysis to combine the inferences from each plausible galaxy to give an overall estimate cite:2019arXiv190806050G,2019arXiv190806060T.

From the first two observation runs' detections it is possible to update the GW170817-only estimate of $H_{0}$ to $\SI[parse-numbers=false]{68.0^{+14.0}_{-7.0}}{\kilo\meter\ \second^{-1}\  \mega\parsec^{-1}}$ \cite{2019arXiv190806060T}.

\begin{figure}
\includegraphics[width=\textwidth]{figures/H0-statistical}
\caption{The posterior probability density function for $H_{0}$ inferred using a statistical method and observations from the O1 and O2 observing runs for advanced LIGO and Virgo. \cite{2019arXiv190806050G,2019arXiv190806060T}}
\label{fig:det:advanced-timing}
\end{figure}

# * Astrophysics from multi-messenger astronomy

# ** Equation of state


* GW follow-up of EM events

In addition to attempts to identify electromagnetic counterparts to abbr:gw signals, there are ongoing efforts to identify abbr:gw signals produced by events observed by abbr:em observatories.
Thanks to the near-continuous, all-sky, broadband observations made by a network of abbr:gw detectors, it is possible to conduct searches for abbr:gw counterparts in high-latency in recorded data (whereas an abbr:em observatory may need to be pointed to the appropriate area of sky, for example).

There have been targeted searches for abpl:gw from abpl:sn, motivated by abbr:em observations. 
The sky localisation provided by the abbr:em observation simplifies the process of searching for the abbr:gw signal cite:2019arXiv190803584T.

Pulsars are the most promising source of continuous abpl:gw, and since these are observed by radio telescopes, which can determine their rotation frequency we can target searches for abpl:gw from pulsars both by sky location and abbr:gw frequency (the abbr:gw frequency is twice the rotation frequency, since abpl:gw are emitted from the quadrupole mode).
To date we've not been successful in detecting abpl:gw from pulsars, but the non-detection allows us to place limits on the physical properties of known pulsars cite:2019PhRvD..99l2002A.
Pulsars are also observed to /glitch/ when observed in radio: a glitch is a sudden change in the rotational frequency of the pulsar; the mechanism which causes these is poorly understood, but may produce abpl:gw.
The time at which these glitches occur is well known from abbr:em observations, so searches for these can be carried out over a short stretch of abbr:gw data cite:2019PhRvD.100f4058K.

Observations are made of abpl:sgrb frequently, and abbr:bns events are known to be a progenitor source for these events.
These events are very well localised in time, however gamma ray detectors are not normally able to give a very precise sky localisation for an event, so a abbr:gw search can be made over a short span of abbr:gw detector data, but a large sky area cite:2019arXiv190701443T.


* The future: multi-band multimessenger astronomy

The current generation of abbr:gw detectors are designed to operate in a frequency range where the merger and ringdown components of a abbr:bns or low-mass abbr:bbh system will produce a detectable signal.
However, space-based detectors, such as gls:lisa, will be able to make observations at much lower frequencies. 
As a result the inspiral of these events will be observable for a much longer period of time than is currently possible.

For an inspiralling abbr:cbc event the frequency of the inspiral signal can be used to predict the time at which the two systems will merge cite:1994PhRvD..50.7111S.
This means if the lowest frequency a detector can measure an inspiral signal at is $f_{\text{low}}$ then the time, $t$, between observing the start of the inspiral and the merger is approximately
\begin{align}
\label{eq:sources:cbc:time-until-coalescence}
t &\approx \frac{5}{256} \left( \frac{G \chirpmass}{c^3} \right)^{-\frac{5}{3}} ( \pi f_{\text{low}} )^{- \frac{8}{3}} \\
  &\approx 2.16 \left(\frac{\chirpmass}{1.22 \solMass} \right)^{-\frac{5}{3}} \left( \frac{f_{\text{low}}}{\SI{100}{\hertz}} \right)^{- \frac{8}{3}} \quad\text{sec}
\end{align}
where $\chirpmass$ is the gls:chirp-mass.
For a abbr:bns system the gls:chirp-mass will be around $\SI{1.25}{\solMass}$.

\begin{figure}
\includegraphics[width=\textwidth]{figures/inspiral-time}
\caption{The physical time until coalescence for an inspiralling binary system, given a chirp mass ($y$-axis), for the system, and a signal frequency ($x$-axis).}
\label{fig:cbc:inspiral-time}
\end{figure}

# ** Exercise
#    Advanced LIGO can detect signals at a frequency around as low as $\SI{10}{\hertz}$, however the third generation Einstein Telescope will be able to make observations down to around $\SI{1}{\hertz}$. What is the increase in observation time achieved between the two detectors for a abbr:bns system?



The amount of advance warning will depend on the strength of the abbr:bns signal, but all abbr:bns within $\SI{40}{\mega\parsec}$ should be localised an hour prior to the merger by third generation detectors cite:2018PhRvD..97l3014C.


* Glossary                                                :glossary:noexport:
#+COLUMNS: %20ITEM %ABBR %ABBRPL
** active galactic nucleus
   :PROPERTIES:
   :ABBR:     AGN
   :END:
   A compact region at the centre of a galaxy which is producing electromagnetic radiation through processes which are not associated with normal stellar radiation processes. 
** binary black hole
   :PROPERTIES:
   :ABBR: BBH
   :ABBRPL: BBHs
   :END:
   A pair of black holes which are in a captured binary orbit of each other. In General Relativity all orbits are unstable, will inspiral, and eventually the black holes will coalesce. This term is normally used of black holes late in the decay of the orbit.
** compact binary coalescence
   :PROPERTIES:
   :ABBR: CBC
   :ABBRPL: CBCs
   :END:
   A pair of compact objects (for example neutron stars or black holes) which are inspiralling, and will eventually merge and coalesce, producing gravitational waves.
** binary neutron star
   :PROPERTIES:
   :ABBR: BNS
   :ABBRPL: BNSs
   :END:
   See \gls{binary-black-hole}, however here the objects are neutron stars rather than black holes.
** chirp mass
   :PROPERTIES:
   :SYMBOL:   $\mathcal{M}$
   :END:
   A  of a compact binary system which determines the frequency evolution of the gravitational waveform emitted during the inspiral.
   It is defined as 
   \begin{equation}
   \mathcal{M} = \frac{(m_1 m_2)^{3 / 5} }{(m_1 + m_2)^{1 / 5}}.
   \end{equation}
** continuous wave
   :PROPERTIES:
   :ABBR:     CW
   :END:
   A category of \gls{gw} signal which is generated by an ongoing process, rather than from a transient burst of energy.
** short gamma-ray burst
   :PROPERTIES:
   :ABBR:     sGRB
   :END:
   Short-duration GRBs were long-suspected to be the electromagnetic
   signature of compact binary coalesence events, and the observation
   of GW170817 in 2017, a binary neutron star coalesence event, and
   its associated gamma ray burst, GRB170817A cemented these CBC
   events as the progenitor of at least some fraction of sGRBs.
** gamma-ray burst
   :PROPERTIES:
   :ABBR:     GRB
   :END:
   Gamma ray bursts are extremely energetic cosmological events which
   are observed to occur around once per day, and appear to be derived
   from at least two separate populations, divided by their duration
   and spectral hardness, although there is overlap and ambiguity
   between the two populations.
** gravitational wave
   :PROPERTIES:
   :ABBR:     GW
   :END:
** Swift Burst Alert Telescope
   :PROPERTIES:
   :ABBR:     BAT
   :END:
** Fermi Gamma-ray Burst Monitor
   :PROPERTIES:
   :ABBR:     GBM
   :END:

** multimessenger astronomy
   :PROPERTIES:
   :ABBR:     MMA
   :END:
   A field of observational astronomy in which observations are made through at least two "messengers", which are each different sources of radiated information, for example electromagnetic radiation and emitted particles.
** electromagnetic 
   :PROPERTIES:
   :ABBR:     EM
   :END:
** high-energy neutrino
   :PROPERTIES:
   :ABBR:     HEN
   :ABBRPL:   HENs
   :END:
** GW170817
   The abbr:gw signal which was provided the first binary neutron star coalescence detection in August 2017.
** Laser Interferometer Space Antenna
   :PROPERTIES:
   :NAME:     LISA
   :ABBR: LISA
   :END:
** Zwicky transient facility
   :PROPERTIES:
   :ABBR:     ZTF
   :END:
** Large synoptic survey telescope
   :PROPERTIES:
   :ABBR:     LSST
   :END:

** Gamma-ray Burst Coordinates Network
   :PROPERTIES:
   :ABBR:     GCN
   :END:
** supernova
   :PROPERTIES:
   :ABBR:     SN
   :ABBRPL:   SNe
   :END:

   A system for distributing information about transient astronomical events, in the form of email /notices/, and observations are reported in the form of /circulars/ through this network.
Recent and archival notices and circulars can be viewed at \url{https://gcn.gsfc.nasa.gov/}.
